runtime: nodejs14

instance_class: F1

env_variables:
  API_KEY: 'Device 8bfec1ab-4b2b-447e-b478-534121c84b26:1mw8ZUzjmKb6kv4wkptZkTZ3ZGFBXCWW'

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

automatic_scaling:
  min_instances: 1
  max_instances: 1
